### ISSUE TITLE
utls.HelloRandomizedALPN doesn't randomize the ciphers or anything

### ISSUE THREAD

**Issue by ghost** [refraction-networking/utls#109]
Hey, why is this code not randomizing the ciphers or the extensions?

Code:
```
uconn = utls.UClient(conn, config, utls.HelloRandomizedALPN)
```

**Comment by Gaukas** [comment]
Hi @kawacode, 

It may take longer to get you an direct answer but you may look into this function here: 
https://github.com/refraction-networking/utls/blob/9d36ce36584651b35280a1ef8fc57e15791820be/u_parrots.go#L699

I don't see any essentially incorrect implementation here but 
https://github.com/refraction-networking/utls/blob/9d36ce36584651b35280a1ef8fc57e15791820be/u_parrots.go#L710
might be something you want to give some detailed look
