### ISSUE TITLE
GREASE key shared extension replaced by unsupported named group

### ISSUE THREAD

**Issue by hohorace** [refraction-networking/utls#111]
Hello!
I have http/2 client that uses the following dialer:
```
type Dialer struct {
       spec *utls.ClientHelloSpec
}

func NewDialer(data []byte) (*Dialer, error ) {
        fingerprinter := &utls.Fingerprinter{}
	spec, err := fingerprinter.FingerprintClientHello(data)
	if err != nil {
		return nil, err
	}
	return &Dialer{spec: spec}
}

func (d *Dialer) DialTLS(network, addr string, cfg *tls.Config) (net.Conn, error) {
	config := &utls.Config{
		ServerName: strings.Split(addr, ":")[0],
		NextProtos: cfg.NextProtos,
	}
	
	dialConn, err := net.Dial(network, addr)
	if err != nil {
		return nil, err
	}

	uTLSConn := utls.UClient(dialConn, cfg, utls.HelloCustom)

	if err := uTLSConn.ApplyPreset(spec); err != nil {
		return nil, err
	}

	if err := uTLSConn.Handshake(); err != nil {
		return nil, err
	}

	return uTLSConn, nil
}
```
this dialer uses a custom client hello spec with a key share extension of value [GREASE, X25519].

When applying the spec to the `UClient`, GREASE is replaced by a random value:
https://github.com/refraction-networking/utls/blob/9d36ce36584651b35280a1ef8fc57e15791820be/u_parrots.go#L662
which made subsequent redials error here:
https://github.com/refraction-networking/utls/blob/9d36ce36584651b35280a1ef8fc57e15791820be/u_parrots.go#L671

Is this the intended behavior? 
What would be the right way to implement this? Creating a new `*utls.ClientHelloSpec` every time when dialing?

Thank you 🙇

**Comment by Gaukas** [comment]
Hi @hohorace, nice catch! It seems that the current design of `ApplyPreset()` will make the input `p *ClientHelloSpec` not reusable. Possibly a temporary solution here without further investigation will be cloning the `p` used. 

This project is always in need of help from our community. It would be greatly appreciated if someone could open a PR addressing this issue.

**Comment by fedosgad** [comment]
Hello!
I've encountered different error with the same root cause. In my case, error was `bad record MAC` (I'm using utls as a grpc TLS layer), and it only happened on a second connection using the same `*ClientHelloSpec`. Cloning helps - error disappears.
If you need it, I can try to make a repro code and post it here.
