### ISSUE TITLE
Impersonate ClientHello with UtlsGREASEExtension 

### ISSUE THREAD

**Issue by chabior** [refraction-networking/utls#128]
Hello

I want to impersonate a request using two Grease Extensions, but when I try to mimic it, a different type value is generated, resulting in a different JA3 fingerprint. 

What I do in code:
`&tls.UtlsGREASEExtension{
			Value: 60138,
		}`

But in wireshark it shows different value with every request
![Screenshot from 2022-10-25 11-10-55](https://user-images.githubusercontent.com/4804789/197733858-90f99167-6d62-4f54-aef4-80bf2a714179.png)

Am I doing something wrong?

**Comment by gaukas** [comment]
iirc `UtlsGREASEExtension` at some point gets replaced by a random value: https://github.com/refraction-networking/utls/blob/862fe372d939c53bb10cb4fd11263f3766589892/u_parrots.go#L1934-L1944

But I second that it would be a good idea if we allow mimicking fixed GREASE value, if a certain GREASE value is at all meaningful.

**Comment by gaukas** [comment]
Perhaps it is a good idea if we check if Value is set (to non-zero) and if so, don't overwrite the value.

**Comment by gaukas** [comment]
Implemented in #139. 

Planning to make it appear in the next tagged version in 2 weeks.

**Comment by gaukas** [comment]
Actually after inspecting your usage, you may want to use `GenericExtension` instead.
