### ISSUE TITLE
What is the relationship between JA3 fingerprint and this type of TLS fingerprint 

### ISSUE THREAD

**Issue by Longway22** [refraction-networking/utls#129]
I have noticed that JA3 fingerprint is MD5 hash, but on [tlsfingerprint.io](https://tlsfingerprint.io/) the fingerprint is exactly not MD5, so I doubt TLS fingerprint in this repo is a different one with JA3 fingerprint?

**Comment by gaukas** [comment]
Only my personal opinion: 
JA3 fingerprint is just another concurrent work to [Dr.Frolov's paper at NDSS'19](https://tlsfingerprint.io/static/frolov2019.pdf) and I expect to see no relation between a JA3 hash and a tlsfingerprint.io hash.
