### ISSUE TITLE
Chrome 107 started shuffling extensions

### ISSUE THREAD

**Issue by gaukas** [refraction-networking/utls#132]
An incomplete list of possible fingerprints used by Chrome 107:

[4c7826a590831f89](https://tlsfingerprint.io/id/4c7826a590831f89)
[54609dcb6ddbf977](https://tlsfingerprint.io/id/54609dcb6ddbf977)
[66bbe813f85045d4](https://tlsfingerprint.io/id/66bbe813f85045d4)
[1a84ca827ce68206](https://tlsfingerprint.io/id/1a84ca827ce68206)
[f4bc6fabac86598a](https://tlsfingerprint.io/id/f4bc6fabac86598a)

Observation indicates the extensions are getting shuffled with every new Client Hello. 

----

To be honest, this kinda defeats the purpose of uTLS (in terms of parroting). 

But I see this as a huge success of uTLS!

**Comment by gaukas** [comment]
We may want to implement Extension randomizer for this.

**Comment by gaukas** [comment]
If anyone observed the same, please upvote this. For now I have difficulties reproduce it on any other devices/setups.

**Comment by 2qif49lt** [comment]
https://tlsfingerprint.io/id/e47eae8f8c4887b6

no change after chrome 106 upgrade to 107

**Comment by bemasc** [comment]
See the announcement [here](https://groups.google.com/a/chromium.org/g/blink-dev/c/zdmNs2rTyVI/m/MAiQwQkwCAAJ)

**Comment by gaukas** [comment]
Ah nice. Thanks @bemasc that's what I've been looking for!

**Comment by 4cq2** [comment]
https://github.com/net4people/bbs/issues/220
