### ISSUE TITLE
HTTP2 + Custom Fingerprints from tlsfingerprint.io

### ISSUE THREAD

**Issue by itschasa** [refraction-networking/utls#137]
Currently, my code only allows http1.1 connections. Here it is: (sorry if its bad, im really bad at go)
```go
package main

import (
	"context"
	"fmt"
	"io/ioutil"
	"net"
	"net/http"
	"net/http/cookiejar"

	tls "github.com/refraction-networking/utls"
)

func main() {
    cookieJar, _ := cookiejar.New(nil)

    client := &http.Client{
		Jar: cookieJar,
		Transport: &http.Transport{
			DialTLSContext: func(ctx context.Context, network, addr string) (net.Conn, error) {
				// Note that hardcoding the address is not necessary here. Only
				// do that if you want to ignore the DNS lookup that already
				// happened behind the scenes.
	
				tcpConn, err := (&net.Dialer{}).DialContext(ctx, network, addr) 
				if err != nil {
					return nil, err
				}
				config := tls.Config{ServerName: "tls.peet.ws"}
				tlsConn := tls.UClient(tcpConn, &config, tls.HelloChrome_102)
	
				err = tlsConn.Handshake()
				if err != nil {
					return nil, fmt.Errorf("uTlsConn.Handshake() error: %w", err)
				}
	
				return tlsConn, nil
			},
		},
	}

    req, err := http.NewRequest("GET", "https://tls.peet.ws/api/all", nil)
    req.Header.Add("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36")

    resp, err := client.Do(req)
    if err != nil {
        fmt.Println(err)
    } else {
        fmt.Println(resp.StatusCode)
        body, _ := ioutil.ReadAll(resp.Body)
        fmt.Println(string(body))
    }
}
```

I wanted to know how I can implement http2 into this, and also how to use fingerprint IDs ([e47eae8f8c4887b6](https://tlsfingerprint.io/id/e47eae8f8c4887b6)) from tlsfingerprint.io
Thank you! Sorry if I'm being really stupid. I tried to look around for info, but couldn't find any.

**Comment by gaukas** [comment]
Hi @itschasa, for H2 transport, you might want to have 

```go
&http.Client{Transport: &http2.Transport{
	DialTLS:            utlsDial,
	DisableCompression: true,
	AllowHTTP:          false,
}}
```

Where `utlsDial()` is defined as

```go
func utlsDial(_, addr string, _ *ctls.Config) (net.Conn, error) {
	tcpConn, err := net.Dial("tcp4", addr)
	if err != nil {
		return nil, err
	}

	tlsConn := tls.UClient(tcpConn, &tls.Config{
		ServerName: "gauk.as",
	},
		tls.HelloChrome_102)

	err = tlsConn.Handshake()
	if err != nil {
		return nil, err
	}

	return tlsConn, nil
}
```

Note that `crypto/tls.Config` isn't fully compatible with `utls.Config`, so you might need a config translation process for it to work if you don't want to hardcode a `utls.Config` just like what I did.

**Comment by gaukas** [comment]
> and also how to use fingerprint IDs ([e47eae8f8c4887b6](https://tlsfingerprint.io/id/e47eae8f8c4887b6)) from tlsfingerprint.io

For now unfortunately you can't use it directly. You need to use the code generator on [tlsfingerprint.io](https://tlsfingerprint.io/) and generate uTLS code. We are considering ways to integrate tlsfingerprint.io `ClientHelloSpec` in uTLS, but we can't provide any progress or ETA guarantee on that. 

Note: the code generator on tlsfingerprint.io is very much OUTDATED. You may need to refer to all known fingerprints in `utlsIdToSpec()` and make necessary modifications since some said `UNKNOWN` extensions are actually implemented in uTLS.

**Comment by itschasa** [comment]
ok, thank you so much for your help!

**Comment by AeonLucid** [comment]
Hey @gaukas, I used your example to configure a parroted uTLS connection. My `ClientHelloSpec` has the AlpnProtocols `h2` and `http/1.1`. Most of the servers I connect with support HTTP2, but there are a few that require HTTP 1.1.

Using your example I get `unexpected EOF` when calling a HTTP 1.1 server. Do you have an example that would also support HTTP 1.1, or would this require me to create another transport just for 1.1?

**Comment by gaukas** [comment]
Hi @AeonLucid, to support both HTTP/1.1 and H2 it may require some hacking, I would recommend using https://github.com/imroc/req 

In its discussion section there is an example of how to incorporate uTLS with it.
