### ISSUE TITLE
v1.2.0 Refactor the code and allow custom handshake messages

### ISSUE THREAD

**Issue by gaukas** [refraction-networking/utls#140]
We are planning to do the first major refactorization to improve the programmability, in order to support `ALPS` and more future extensions to come. 

More details to come... ~This may lead to a major version bump (`v1` -> `v2`)~ We are trying to minimize the incompatibility and not planning for a major version bump. 

- [x] #133 
- [x] #138  
- [x] #142

**Comment by packman80** [comment]
Great changes! Thank you @gaukas
