### ISSUE TITLE
Small chance that generated fingerprint won't work

### ISSUE THREAD

**Issue by ghost** [refraction-networking/utls#145]
> But note that there's a small chance that generated fingerprint won't work, so you may want to keep generating until a working one is found, and then keep reusing the working fingerprint to avoid suspicious behavior of constantly changing fingerprints. [utls.Roller](https://github.com/refraction-networking/utls#roller) reuses working fingerprint automatically.

Why is there a small chance that generated fingerprint won't work?

**Comment by gaukas** [comment]
Possibly due to middleboxes or anti-bot (maybe anti-human) checking?
