### ISSUE TITLE
update crypto/tls: let HTTP/1.1 clients connect to servers with NextProtos "h2" and crypto/ecdsa: use bigmod and nistec instead of math/big and crypto/el…

### ISSUE THREAD

**Issue by Potterli20** [refraction-networking/utls#150]
[update](https://github.com/refraction-networking/utls/pull/147/commits/35f71c45a8c45dd842b06014715eb16afc0b4410) https://github.com/golang/go/commit/dc00dc6c6bf3b5554e37f60799aec092276ff807 [and](https://github.com/refraction-networking/utls/pull/147/commits/35f71c45a8c45dd842b06014715eb16afc0b4410) https://github.com/golang/go/commit/08f2091ce0817346458d2ae984ccea77817cd516

**Comment by gaukas** [comment]
Hi @Potterli20, thanks for the PR. I see the workflow test has failed on your recent commit, would you like to provide some more information on your commits? In effect all the past commits made to crypto/tls has been merged into this branch in #130.

**Comment by gaukas** [comment]
> fail in the trojan-go-fork test

No I mean, it is failing the `go test` for utls and therefore I would not be able to merge it.
