### ISSUE TITLE
Can update library based on the latest chrome version?

### ISSUE THREAD

**Issue by magdev2022** [refraction-networking/utls#152]
Hello, I think current utls is based on chrome102. 
can update utls based on the chrome108 or 109?

**Comment by gaukas** [comment]
Hello @magdev2022,

Chrome 102 and above essentially used the same fingerprint. Starting Chrome 106 they have introduced shuffling in TLS Extensions (A/B test in Chrome 106, now for all). You may use `HelloChrome_106_Shuffle` for now and we will point `HelloChrome_Auto` to it in the next tagged version.
