### ISSUE TITLE
Using utls with `http.Transport`

### ISSUE THREAD

**Issue by AxbB36** [refraction-networking/utls#16]
I'm using commit a89e7e6da482a5a0db02578fc606ace9ccfbea62. The examples I have found of using utls with HTTPS all make a single request on a single connection, then throw the connection away. For example, [`httpGetOverConn`](https://github.com/refraction-networking/utls/blob/a89e7e6da482a5a0db02578fc606ace9ccfbea62/examples/examples.go#L318) in examples.go.

I'm trying to use utls with [`http.Transport`](https://golang.org/pkg/net/http/#Transport), to take advantage of persistent connections and reasonable default timeouts. To do this, I'm hooking into the `DialTLS` callback. There is a problem when using a utls fingerprint that includes `h2` in ALPN and a server that supports HTTP/2. The server switches to HTTP/2 mode, but the client stays in HTTP/1.1 mode, because net/http [disables automatic HTTP/2 support whenever `DialTLS` is set](https://github.com/golang/go/blob/a2bb68de4d1cb1ca35279523365e9caf36fb9896/src/net/http/transport.go#L299-L306). The end result is an HTTP/1.1 client speaking to an HTTP/2 server; i.e, a similar problem as what was reported in https://github.com/golang/go/issues/14275#issue-132513041. The error message differs depending on the fingerprint:
<dl>
<dt><code>HelloFirefox_63</code></dt>
<dd><code>net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x00\x00\x12\x04\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00d\x00\x04\x00\x10\x00\x00\x00\x06\x00\x00@\x00\x00\x00\x04\b\x00\x00\x00\x00\x00\x00\x0f\x00\x01\x00\x00\x1e\a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01http2_handshake_failed"</code></dt>
<dt><code>HelloChrome_70</code></dt>
<dd><code>local error: tls: unexpected message</code></dd>
<dt><code>HelloIOS_11_1</code></dt>
<dd><code>2019/01/11 14:48:56 Unsolicited response received on idle HTTP channel starting with "\x00\x00\x12\x04\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00d\x00\x04\x00\x10\x00\x00\x00\x06\x00\x00@\x00\x00\x00\x04\b\x00\x00\x00\x00\x00\x00\x0f\x00\x01"; err=&lt;nil&gt;<br>
readLoopPeekFailLocked: &lt;nil&gt;</code></dd>
</dl>

I get the same results even if I pre-configure the `http.Transport` with HTTP/2 support by calling `http2.ConfigureTransport(tr)`.

I wrote a test program to reproduce these results. It takes a `-utls` option to select a utls client hello ID, and a `-callhandshake` option to control whether to call [`UConn.Handshake`](https://godoc.org/github.com/refraction-networking/utls#UConn.Handshake) within `DialTLS`, or allow it to be called implicitly by the next `Read` or `Write`. I included the latter option because I found that not calling `UConn.Handshake` inside `DialTLS` avoids the HTTP version mismatch; however it also results in a client hello that lacks ALPN and differs from the requested one in other ways, so it's not an adequate workaround.
<details>
<summary>Click to expand program</summary>

```
package main

import (
	"flag"
	"fmt"
	"io"
	"io/ioutil"
	"net"
	"net/http"
	"os"
	"strings"

	utls "github.com/refraction-networking/utls"
)

func main() {
	utlsClientHelloIDName := flag.String("utls", "", "use utls with the given ClientHelloID (e.g. HelloGolang)")
	callHandshake := flag.Bool("callhandshake", false, "call UConn.Handshake inside DialTLS")
	flag.Parse()

	if *callHandshake && *utlsClientHelloIDName == "" {
		fmt.Fprintf(os.Stderr, "error: -callhandshake only makes sense with -utls\n")
		os.Exit(1)
	}

	if flag.NArg() != 1 {
		fmt.Fprintf(os.Stderr, "error: need a URL\n")
		os.Exit(1)
	}
	url := flag.Arg(0)

	utlsClientHelloID, ok := map[string]*utls.ClientHelloID{
		"":                      nil,
		"HelloGolang":           &utls.HelloGolang,
		"HelloRandomized":       &utls.HelloRandomized,
		"HelloRandomizedALPN":   &utls.HelloRandomizedALPN,
		"HelloRandomizedNoALPN": &utls.HelloRandomizedNoALPN,
		"HelloFirefox_Auto":     &utls.HelloFirefox_Auto,
		"HelloFirefox_55":       &utls.HelloFirefox_55,
		"HelloFirefox_56":       &utls.HelloFirefox_56,
		"HelloFirefox_63":       &utls.HelloFirefox_63,
		"HelloChrome_Auto":      &utls.HelloChrome_Auto,
		"HelloChrome_58":        &utls.HelloChrome_58,
		"HelloChrome_62":        &utls.HelloChrome_62,
		"HelloChrome_70":        &utls.HelloChrome_70,
		"HelloIOS_Auto":         &utls.HelloIOS_Auto,
		"HelloIOS_11_1":         &utls.HelloIOS_11_1,
	}[*utlsClientHelloIDName]
	if !ok {
		fmt.Fprintf(os.Stderr, "unknown client hello ID %q\n", *utlsClientHelloIDName)
		os.Exit(1)
	}

	tr := http.DefaultTransport.(*http.Transport)
	if utlsClientHelloID != nil {
		tr.DialContext = nil
		tr.Dial = func(network, addr string) (net.Conn, error) { panic("Dial should not be called") }
		tr.DialTLS = func(network, addr string) (net.Conn, error) {
			fmt.Printf("DialTLS(%q, %q)\n", network, addr)
			if tr.TLSClientConfig != nil {
				fmt.Printf("warning: ignoring TLSClientConfig %v\n", tr.TLSClientConfig)
			}
			conn, err := net.Dial(network, addr)
			if err != nil {
				return nil, err
			}
			uconn := utls.UClient(conn, nil, *utlsClientHelloID)
			colonPos := strings.LastIndex(addr, ":")
			if colonPos == -1 {
				colonPos = len(addr)
			}
			uconn.SetSNI(addr[:colonPos])
			if *callHandshake {
				err = uconn.Handshake()
			}
			return uconn, err
		}
	}

	for i := 0; i < 4; i++ {
		resp, err := get(tr, url)
		if err != nil {
			fmt.Printf("%2d err %v\n", i, err)
		} else {
			fmt.Printf("%2d %s %s\n", i, resp.Proto, resp.Status)
		}
	}
}

func get(rt http.RoundTripper, url string) (*http.Response, error) {
	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		return nil, err
	}
	resp, err := rt.RoundTrip(req)
	if err != nil {
		return nil, err
	}
	// Read and close the body to enable connection reuse with HTTP/1.1.
	_, err = io.Copy(ioutil.Discard, resp.Body)
	if err != nil {
		return nil, err
	}
	err = resp.Body.Close()
	if err != nil {
		return nil, err
	}
	return resp, nil
}
```
</details>

Sample usage:
```
test -utls HelloFirefox_63 -callhandshake https://golang.org/robots.txt
```

The output of the program appears in the following table. Things to notice:
* `DialTLS` with `HelloGolang` produces a fingerprint that is different from using `http.Transport` without `DialTLS` set.
* `HelloFirefox_63`, `HelloChrome_70`, and `HelloIOS_11_1` all provide a usable connection (but with an incorrect fingerprint), as long as you don't call `UConn.Handshake` before returning from `DialTLS`.
* `HelloFirefox_63`, `HelloChrome_70`, and `HelloIOS_11_1` all give the correct fingerprint, but fail with an HTTP version mismatch, when `UConn.Handshake` is called inside `DialTLS`.

| Client Hello ID         | call `Handshake`? | client ALPN    | result |
| ----------------------- | ----------------- | -------------- | ------------ |
| *none*                  | N/A               | [h2, http/1.1] | ok HTTP/2    |
| `-utls HelloGolang`     |                   | *none*         | ok HTTP/1.1  |
| `-utls HelloGolang`     | `-callhandshake`  | *none*         | ok HTTP/1.1  |
| `-utls HelloFirefox_63` |                   | *none*         | ok HTTP/1.1  |
| `-utls HelloFirefox_63` | `-callhandshake`  | [h2, http/1.1] | `malformed HTTP response` (HTTP/1.1 client, HTTP/2 server) |
| `-utls HelloChrome_70`  |                   | *none*         | ok HTTP/1.1  |
| `-utls HelloChrome_70`  | `-callhandshake`  | [h2, http/1.1] | `local error: tls: unexpected message` |
| `-utls HelloIOS_11_1`   |                   | *none*         | ok HTTP/1.1  |
| `-utls HelloIOS_11_1`   | `-callhandshake`  | [h2, h2-16, h2-15, h2-14, spdy/3.1, spdy/3, http/1.1] | `readLoopPeekFailLocked: <nil>` (HTTP/1.1 client, HTTP/2 server) |

Is there a way to accomplish what I am trying to do?

**Comment by AxbB36** [comment]
I had some success by switching [`http2.Transport`](https://godoc.org/golang.org/x/net/http2#Transport) for `http.Transport`:
```diff
 package main
 
 import (
+	gotls "crypto/tls"
 	"flag"
 	"fmt"
 	"io"
@@ -11,6 +12,7 @@ import (
 	"strings"
 
 	utls "github.com/refraction-networking/utls"
+	"golang.org/x/net/http2"
 )
 
 func main() {
@@ -51,20 +53,15 @@ func main() {
 		os.Exit(1)
 	}
 
-	tr := http.DefaultTransport.(*http.Transport)
+	tr := &http2.Transport{}
 	if utlsClientHelloID != nil {
-		tr.DialContext = nil
-		tr.Dial = func(network, addr string) (net.Conn, error) { panic("Dial should not be called") }
-		tr.DialTLS = func(network, addr string) (net.Conn, error) {
+		tr.DialTLS = func(network, addr string, cfg *gotls.Config) (net.Conn, error) {
 			fmt.Printf("DialTLS(%q, %q)\n", network, addr)
-			if tr.TLSClientConfig != nil {
-				fmt.Printf("warning: ignoring TLSClientConfig %v\n", tr.TLSClientConfig)
-			}
 			conn, err := net.Dial(network, addr)
 			if err != nil {
 				return nil, err
 			}
-			uconn := utls.UClient(conn, nil, *utlsClientHelloID)
+			uconn := utls.UClient(conn, &utls.Config{NextProtos: cfg.NextProtos}, *utlsClientHelloID)
 			colonPos := strings.LastIndex(addr, ":")
 			if colonPos == -1 {
 				colonPos = len(addr)
```

These are the results using the URL `https://golang.org/robots.txt`. Notice:
* The output is the same whether `UConn.Handshake` is called within `DialTLS` or not.
* The `HelloChrome_70` fingerprint doesn't work.

| Client Hello ID         | call `Handshake`? | client ALPN    | result |
| ----------------------- | ----------------- | -------------- | ------------ |
| *none*                  | N/A               | [h2]           | ok HTTP/2    |
| `-utls HelloGolang`     |                   | [h2]           | ok HTTP/2    |
| `-utls HelloGolang`     | `-callhandshake`  | [h2]           | ok HTTP/2    |
| `-utls HelloFirefox_63` |                   | [h2, http/1.1] | ok HTTP/2    |
| `-utls HelloFirefox_63` | `-callhandshake`  | [h2, http/1.1] | ok HTTP/2    |
| `-utls HelloChrome_70`  |                   | [h2, http/1.1] | `local error: tls: unexpected message` |
| `-utls HelloChrome_70`  | `-callhandshake`  | [h2, http/1.1] | `local error: tls: unexpected message` |
| `-utls HelloIOS_11_1`   |                   | [h2, h2-16, h2-15, h2-14, spdy/3.1 spdy/3 http/1.1] | ok HTTP/2  |
| `-utls HelloIOS_11_1`   | `-callhandshake`  | [h2, h2-16, h2-15, h2-14, spdy/3.1 spdy/3 http/1.1] | ok HTTP/2  |

Aside from the `HelloChrome_70` failure, this is basically what I want. The only problem is that it doesn't work against non-HTTP/2 servers, whether utls is used or not:
```
$ test https://apache.org/
 0 err http2: unexpected ALPN protocol "http/1.1"; want "h2"
 1 err http2: unexpected ALPN protocol "http/1.1"; want "h2"
 2 err http2: unexpected ALPN protocol "http/1.1"; want "h2"
 3 err http2: unexpected ALPN protocol "http/1.1"; want "h2"
```
```
$ test -utls HelloGolang -callhandshake https://apache.org/
DialTLS("tcp", "apache.org:443")
 0 err unexpected EOF
DialTLS("tcp", "apache.org:443")
 1 err unexpected EOF
DialTLS("tcp", "apache.org:443")
 2 err unexpected EOF
DialTLS("tcp", "apache.org:443")
 3 err unexpected EOF
```

**Comment by AxbB36** [comment]
Yawning has a commit adding uTLS to obfs4proxy's meek_lite mode:
https://gitlab.com/yawning/obfs4/commit/4d453dab2120082b00bf6e63ab4aaeeda6b8d8a3
It uses an I idea I didn't think of. Instead of setting `DialTLS` on an `http.Transport` and using it directly, it uses a wrapper `http.RoundTripper`. On the first dial, the wrapper initiates the `UClient` connection, then inspects `conn.ConnectionState().NegotiatedProtocol`. Depending on the negotiated protocol, it creates internally either an `http.Transport` or `http2.Transport`. Future dials are passed through to the internal transport directly.

**Comment by sergeyfrolov** [comment]
This is a terrific solution. I'd like to get a wrapper like this into uTLS.

**Comment by Yawning** [comment]
Note that my implementation makes certain assumptions that may not be valid for a more general wrapper (omits some locking, destination host is assumed to be static), but there's comments where I do such things, and altering the behavior should be trivial.

**Comment by zanitee** [comment]
> 
> 
> This is a terrific solution. I'd like to get a wrapper like this into uTLS.

Was there ever a proper soloution to use uTLS with the net/http Client?

**Comment by sergeyfrolov** [comment]
[Comments above](https://github.com/refraction-networking/utls/issues/16#issuecomment-455982018) describe a proper solution.  
This wrapper had not been implemented in uTLS yet.
![image](https://user-images.githubusercontent.com/5443147/57049547-b9560680-6c35-11e9-80bd-f2135ce9a27d.png)

**Comment by zanitee** [comment]
> 
> 
> Note that my implementation makes certain assumptions that may not be valid for a more general wrapper (omits some locking, destination host is assumed to be static), but there's comments where I do such things, and altering the behavior should be trivial.

I'm trying to write a wrapper for net.http Client based on your soloution. Am I right in thinking that I would need to execute getTransport() for every new host and do some kind of connection pooling for effeciency?

**Comment by pharaohW** [comment]
the DialTLS says it's for non-proxied HTTPS requests，But if I want to make requests with transport and proxy，How to make that？

**Comment by AxbB36** [comment]
> the DialTLS says it's for non-proxied HTTPS requests，But if I want to make requests with transport and proxy，How to make that？

There are some code samples here, from the uTLS integration into meek. Adding uTLS was this commit:
 * [Integrate uTLS as an option for TLS camouflage.](https://gitweb.torproject.org/pluggable-transports/meek.git/commit/?id=b8fb876145cda3c14d335a3fc88b5e422a926150)

Adding proxy support was these commits:
 * [socks5 proxy support for uTLS.](https://gitweb.torproject.org/pluggable-transports/meek.git/commit/?id=70c28e34dca7125895921c4161033666148dc3f0)
 * [http proxy support for uTLS.](https://gitweb.torproject.org/pluggable-transports/meek.git/commit/?id=92400c9d9191fe7b661086128639f7f228f5b9e2)
 * [https proxy support for uTLS.](https://gitweb.torproject.org/pluggable-transports/meek.git/commit/?id=4290a67a65a98303b2feb34a230ab23daabb9895)

**Comment by kkotowick** [comment]
The problem (or at least part of it) appears to be here: https://github.com/golang/go/blob/ea1437a8cdf6bb3c2d2447833a5d06dbd75f7ae4/src/net/http/transport.go#L1496

The `http` library determines whether to use `h2` or not by evaluating the `pconn.tlsState` field, which gets set here: https://github.com/golang/go/blob/ea1437a8cdf6bb3c2d2447833a5d06dbd75f7ae4/src/net/http/transport.go#L1513

Since it fails to cast the conn to a `tls.Conn` (since it's a `utls.Conn`, which implements the same `net.Conn` interface but cannot be cast to a `tls.Conn`), it doesn't set the `pconn.tlsState` field, and therefore doesn't know later on that it's an `h2` connection.

What would be ideal is some way to convert a `utls.Conn` to a `tls.Conn` (which shouldn't pose any issues once the handshake is already completed, I think?), and return that from the `DialTLSContext` custom function.

**Comment by molon** [comment]
> > the DialTLS says it's for non-proxied HTTPS requests，But if I want to make requests with transport and proxy，How to make that？
> 
> There are some code samples here, from the uTLS integration into meek. Adding uTLS was this commit:
> 
> * [Integrate uTLS as an option for TLS camouflage.](https://gitweb.torproject.org/pluggable-transports/meek.git/commit/?id=b8fb876145cda3c14d335a3fc88b5e422a926150)
> 
> Adding proxy support was these commits:
> 
> * [socks5 proxy support for uTLS.](https://gitweb.torproject.org/pluggable-transports/meek.git/commit/?id=70c28e34dca7125895921c4161033666148dc3f0)
> * [http proxy support for uTLS.](https://gitweb.torproject.org/pluggable-transports/meek.git/commit/?id=92400c9d9191fe7b661086128639f7f228f5b9e2)
> * [https proxy support for uTLS.](https://gitweb.torproject.org/pluggable-transports/meek.git/commit/?id=4290a67a65a98303b2feb34a230ab23daabb9895)

Very exciting solution.
I try to make some changes to it, because I especially need a response to `req.Context`. For example, in `httpProxy.Dial` transformed into` httpProxy.DialContext`.
But in the follow-up, I found that by default, `http2.Transport` is used directly, and it internally initializes` http2clientConnPool` instead of `http2noDialClientConnPool`. So its` dial` does not use the logic of `http.Transport`, which causes it to be used in` dial` Does not support `req.Context` response.

**Comment by 1nfility** [comment]
Is there any way to use the RoundTripper solution with a Client so you can set Redirect handler and proxy?

**Comment by 89z** [comment]
Using the below program, I also get the `malformed HTTP response`. However I noticed that if I instead use `tls.HelloGolang`, it works. So maybe we can see what the difference is and make correction.

~~~go
package main

import (
   "bufio"
   "fmt"
   "github.com/refraction-networking/utls"
   "net"
   "net/http"
)

func main() {
   req, err := http.NewRequest("HEAD", "https://example.com", nil)
   if err != nil {
      panic(err)
   }
   nConn, err := net.Dial("tcp", req.URL.Host + ":" + req.URL.Scheme)
   if err != nil {
      panic(err)
   }
   cfg := &tls.Config{ServerName: req.URL.Host}
   tConn := tls.UClient(nConn, cfg, tls.HelloChrome_83)
   req.Write(tConn)
   res, err := http.ReadResponse(bufio.NewReader(tConn), req)
   if err != nil {
      panic(err)
   }
   fmt.Printf("%+v\n", res)
}
~~~

**Comment by 89z** [comment]
Looks like someone solved this with another package:

https://godocs.io/github.com/Jarijaas/go-tls-exposed/http#Transport.TLSClientConfig

**Comment by AxbB36** [comment]
This comment is just to report a negative result, an idea I had that turned out not to work. Setting [`ForceAttemptHTTP2`](https://pkg.go.dev/net/http#Transport.ForceAttemptHTTP2) to true on an `http.Transport` that uses a uTLS dialer does not suffice to negotiate an HTTP/2 session. This is probably for the reason @KyleKotowick noted in https://github.com/refraction-networking/utls/issues/16#issuecomment-624076510.

When this issue was crated, go1.11 was current. go1.13 [added `Transport.ForceAttemptHTTP2`](https://go.dev/doc/go1.13#net/http):
> The new field `Transport.ForceAttemptHTTP2` controls whether HTTP/2 is enabled when a non-zero `Dial`, `DialTLS`, or `DialContext` func or `TLSClientConfig` is provided.

The commits that added this field are https://github.com/golang/go/commit/94e720059f902339699b8bf7b2b10897311b50f8 and https://github.com/golang/go/commit/2a931bad4e4d7eabdb685b6dc74406373ad6e7e4.

The following example program shows that setting `ForceAttemptHTTP2` does not work; the client negotiates HTTP/1 even when the server supports HTTP/2. This is not too surprising, since [`DefaultTransport`](https://pkg.go.dev/net/http#DefaultTransport) has `ForceAttemptHTTP2: true`.

<details>
<summary>demo.go</summary>

<pre>
// Demonstration that setting net/http Transport.ForceAttemptHTTP2 to true does
// not suffice to enable HTTP/2 support when its dialer returns a *utls.Conn,
// rather than a *tls.Conn.
package main

import (
	"context"
	"flag"
	"fmt"
	"net"
	"net/http"
	"os"

	utls "github.com/refraction-networking/utls"
)

var utlsClientHelloID = &amp;utls.HelloFirefox_65

// utlsDialContext connects to the given network address and initiates a TLS
// handshake with the provided ClientHelloID, and returns the resulting TLS
// connection.
func utlsDialContext(ctx context.Context, network, addr string, config *utls.Config, id *utls.ClientHelloID) (*utls.UConn, error) {
	// Set the SNI from addr, if not already set.
	if config == nil {
		config = &amp;utls.Config{}
	}
	if config.ServerName == "" {
		config = config.Clone()
		host, _, err := net.SplitHostPort(addr)
		if err != nil {
			return nil, err
		}
		config.ServerName = host
	}
	dialer := &amp;net.Dialer{}
	conn, err := dialer.DialContext(ctx, network, addr)
	if err != nil {
		return nil, err
	}
	uconn := utls.UClient(conn, config, *id)
	// Manually remove the SNI if it contains an IP address.
	// https://github.com/refraction-networking/utls/issues/96
	if net.ParseIP(config.ServerName) != nil {
		err := uconn.RemoveSNIExtension()
		if err != nil {
			uconn.Close()
			return nil, err
		}
	}
	// We must call Handshake before returning, or else the UConn may not
	// actually use the selected ClientHelloID. It depends on whether a Read
	// or a Write happens first. If a Read happens first, the connection
	// will use the normal crypto/tls fingerprint. If a Write happens first,
	// it will use the selected fingerprint as expected.
	// https://github.com/refraction-networking/utls/issues/75
	err = uconn.Handshake()
	if err != nil {
		uconn.Close()
		return nil, err
	}
	return uconn, nil
}

func fetch(url string) error {
	transport := http.DefaultTransport.(*http.Transport).Clone()
	transport.DialTLSContext = func(ctx context.Context, network, addr string) (net.Conn, error) {
		return utlsDialContext(ctx, network, addr, nil, utlsClientHelloID)
	}
	transport.ForceAttemptHTTP2 = true
	client := http.Client{
		Transport: transport,
	}
	resp, err := client.Get(url)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	fmt.Println(resp.Proto)
	return nil
}

func main() {
	flag.Parse()
	if flag.NArg() != 1 {
		fmt.Fprintf(os.Stderr, "usage: %s URL\n", os.Args[0])
		os.Exit(1)
	}
	err := fetch(flag.Arg(0))
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
</pre>
</details>

```
$ go run -- demo.go https://cloudflare.com/
Get "https://cloudflare.com/": net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x00\x00\x12\x04\x00\x00\x00\x00\x00\x00\x03\x00\x00\x01\x00\x00\x04\x00\x01\x00\x00\x00\x05\x00\xff\xff\xff\x00\x00\x04\b\x00\x00\x00\x00\x00\u007f\xff\x00\x00\x00\x00\b\a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01"
exit status 1
```

**Comment by KawaCode** [comment]
Anyone solved this issue ?

**Comment by 89z** [comment]
If you don't need HTTP/2, you can already do this:

https://github.com/89z/format/blob/v1.35.9/crypto/crypto.go#L98-L120

which in most (all?) cases you don't. You just tell the server that you can only handle HTTP/1.1:

https://github.com/89z/format/blob/v1.35.9/crypto/parse.go#L81-L85

**Comment by KawaCode** [comment]
> Is there any way to use the RoundTripper solution with a Client so you can set Redirect handler and proxy?

Yes, there is, i will soon publish the solution, cuz right now i dont got time.

**Comment by 4cq2** [comment]
if it helps, I came up with the below implementation of `http.RoundTripper`. It only supports HTTP/1.1, but might be helpful to some users:

~~~go
package tls

import (
   "bufio"
   "github.com/refraction-networking/utls"
   "net"
   "net/http"
)

type Transport struct {
   Conn *tls.UConn
   Spec tls.ClientHelloSpec
}

func (t *Transport) RoundTrip(req *http.Request) (*http.Response, error) {
   config := tls.Config{ServerName: req.URL.Host}
   conn, err := net.Dial("tcp", req.URL.Host+":443")
   if err != nil {
      return nil, err
   }
   t.Conn = tls.UClient(conn, &config, tls.HelloCustom)
   if err := t.Conn.ApplyPreset(&t.Spec); err != nil {
      return nil, err
   }
   if err := req.Write(t.Conn); err != nil {
      return nil, err
   }
   return http.ReadResponse(bufio.NewReader(t.Conn), req)
}
~~~

**Comment by gaukas** [comment]
Don't know if anyone is still concerned with this stale issue, but if the purpose is simply for building HTTP Clients with uTLS as the tls stack, [imroc/req](https://github.com/imroc/req) seemed to be a good choice. See https://github.com/imroc/req/discussions/198 for multiple different ways you may use uTLS with [imroc/req](https://github.com/imroc/req). 

Closing this for now, but if issue not considered resolved we may reopen it.
