### ISSUE TITLE
u_parrots: needless assignment to hello.CipherSuites

### ISSUE THREAD

**Issue by 4cq2** [refraction-networking/utls#183]
I see this:

https://github.com/refraction-networking/utls/blob/c785bd3a1e8dd394d36526a2f3f118a21fc002c5/u_parrots.go#L2039-L2041

which never does anything, because below you have this:

<https://github.com/refraction-networking/utls/blob/c785bd3a1e8dd394d36526a2f3f118a21fc002c5/u_parrots.go#L2060>

looks like the first of the two lines is a relic from an older version of the code:

<https://github.com/refraction-networking/utls/blob/cd3d1c46563b70b55c209ef96d28ab257cd43121/u_parrots.go#L75-L82>

that never got removed.

**Comment by gaukas** [comment]
Good catch. I agree that the line 2039-2041 should be removed.
