### ISSUE TITLE
invalid Close calls

### ISSUE THREAD

**Issue by ghost** [refraction-networking/utls#188]
all these close calls are invalid:

https://github.com/refraction-networking/utls/blob/c785bd3a1e8dd394d36526a2f3f118a21fc002c5/examples/examples.go#L34

you can test it. after here:

https://github.com/refraction-networking/utls/blob/c785bd3a1e8dd394d36526a2f3f118a21fc002c5/examples/examples.go#L351-L356

insert this:

~~~go
err = response.Body.Close()
fmt.Println(err)
return
~~~

result:

~~~
read tcp 192.168.0.4:58726->31.13.72.36:443: use of closed network connection
~~~

**Comment by 4cq2** [comment]
looks like the issue is only on some servers - if you change Host to `www.example.com` the error goes away

**Comment by gaukas** [comment]
Would love a following-up on this issue. Do we have more details about this error?

**Comment by 1268** [comment]
the issue should be reproducible - did you try steps outlined in the original comment?

**Comment by 1268** [comment]
from my own experience, you need to close the response body BEFORE you close the TLS connection. if that's already whats happening, then we might need to do more research

**Comment by gaukas** [comment]
> close the response body BEFORE you close the TLS connection.

Is this behavior specified somewhere? 

Actually I think the example is overall outdated and poorly designed. The `httpGetOverConn()` is not really making sense as no `ALPN` will be negotiated (no `Config.NextProto` set) and it will always fallback to HTTP/1.1.

**Comment by gaukas** [comment]
>Is this behavior specified somewhere? 

Or lemme rephrase this: What happens if we never close the response body but only the TLS Connection?

**Comment by 1268** [comment]
been a while since I messed with this - I have some code here if it helps:

https://github.com/1268/tls/blob/main/u_common_test.go

at work right now - I can look into this more later if you need
