### ISSUE TITLE
Utls In iran dpi 

### ISSUE THREAD

**Issue by realartin** [refraction-networking/utls#193]
hi there 
tnx for your great work 

according to this tweet 
 [https://twitter.com/uo0sef/status/1668080992052027392?t=cNSQWkDTozhMT9QVOaOHUg&s=19]()

there is an experiment done by uosof that proves dpi in iran can define utls sign packages !

please if it possible make a way for iranian folks that really need your help ❤️🙏

**Comment by gaukas** [comment]
Could you please provide more context of this issue? What worked and what didn't?

**Comment by gaukas** [comment]
After reading the tweet, I think it might not be due to the censor detection, but H2 (HTTP/2 protocol) being negotiated and is not recognized by the program which supports only HTTP/1.

**Comment by gaukas** [comment]
My response here as well: https://twitter.com/_gaukas/status/1671201903072661505
