### ISSUE TITLE
Zlib decompression fails

### ISSUE THREAD

**Issue by felipe-linares** [refraction-networking/utls#205]
Seems like a known issue? Tested on facebook.com using the safari TLS.

https://github.com/refraction-networking/utls/pull/95#issuecomment-1190684525

Zlib decompression returns correct `n` but also return `EOF` error.

If you just ignore the error zlib read error it works, but obviously not the ideal scenario.

**Comment by gaukas** [comment]
Hmm. I think currently uTLS supports only `brotli` while the only preset parrot advertising `zlib` is `HelloSafari_16_0`. 

While we would be happy to accept a PR addressing this issue with `zlib` implementation, are there any more recent popular TLS fingerprints advertising `zlib` over `brotli`? (I am guessing Safari?)

**Comment by gaukas** [comment]
Fixed in #206.
