### ISSUE TITLE
X25519Kyber768 Support?

### ISSUE THREAD

**Issue by VeNoMouS** [refraction-networking/utls#234]
Google has announced plans to add support for quantum-resistant encryption algorithms in its Chrome browser, starting with version 116.

"Chrome will begin supporting [X25519Kyber768](https://www.ietf.org/archive/id/draft-tls-westerbaan-xyber768d00-02.html) for establishing symmetric secrets in [TLS](https://en.wikipedia.org/wiki/Transport_Layer_Security), starting in Chrome 116, and available behind a flag in Chrome 115," Devon O'Brien [said](https://blog.chromium.org/2023/08/protecting-chrome-traffic-with-hybrid.html) in a post published Thursday.

Kyber was [chosen](https://thehackernews.com/2022/07/nist-announces-first-four-quantum.html) by the U.S. Department of Commerce's National Institute of Standards and Technology (NIST) as the candidate for general encryption in a bid to tackle future cyber attacks posed by the advent of quantum computing. [Kyber-768](https://pq-crystals.org/kyber/index.shtml) is roughly the security equivalent of [AES-192](https://en.wikipedia.org/wiki/Advanced_Encryption_Standard).

The encryption algorithm has already been adopted by [Cloudflare](https://blog.cloudflare.com/experiment-with-pq/), [Amazon Web Services](https://aws.amazon.com/blogs/security/round-2-post-quantum-tls-is-now-supported-in-aws-kms/), and IBM.

X25519Kyber768 is a hybrid algorithm that combines the output of [X25519](https://www.rfc-editor.org/rfc/rfc7748), an elliptic curve algorithm widely used for key agreement in TLS, and Kyber-768 to create a strong session key to encrypt TLS connections.

**Comment by VeNoMouS** [comment]
nm see its mentioned in #223

**Comment by gaukas** [comment]
Actually, do you see this feature being shipped with 116 and enabled by default? I just updated and didn't see it as expected. My Chrome 116 seemed to be using the same ClientHello message(s) from previous versions.
