### ISSUE TITLE
random Can not connect: tls: first record does not look like a TLS handshake error

### ISSUE THREAD

**Issue by uoosef** [refraction-networking/utls#242]
when im using this package to mask golang default tls fingerprint i randomly encounter with this error
```bash
Can not connect: tls: first record does not look like a TLS handshake
```

**Comment by gaukas** [comment]
Would you like to provide an example on how did you 

> mask golang default tls fingerprint

**Comment by uoosef** [comment]
i fixed this issue in my code it wasnt the utls problem the irans dpi was dropping packets
