### ISSUE TITLE
Unable to set `OmitEmptyPsk` in `PreSharedKeyExtension`

### ISSUE THREAD

**Issue by sleeyax** [refraction-networking/utls#255]
Not sure if this is considered a bug, but setting `OmitEmptyPsk` to `true` in the `PreSharedKeyExtension` as part of a custom `ClientHelloSpec` has no effect:

```go
spec := &utls.ClientHelloSpec{
    Extensions: []utls.TLSExtension{
        // ...
        &utls.UtlsPreSharedKeyExtension{
            OmitEmptyPsk: true,
        },
    },
}
```

The only way to actually enable `OmitEmptyPsk` is by specifying it in the `UConn` config:

```go
tlsConfig := &utls.Config{OmitEmptyPsk: true}
conn := utls.UClient(rawConn, tlsConfig, tls.HelloCustom)
// ...
```

Because it's overwritten in: 

https://github.com/refraction-networking/utls/blob/1880d7866972add58bdaf1023135200dcbed4f8f/u_session_controller.go#L291

I think this can be fixed/clarified by either making this field private in the extension or by following the configuration in both parts of the code.

Edit: At the time of writing, I'm using the `master` branch with commit 3546fd9286203c4188b0e3f2f01ae7b047552fb5 as the latest change.

**Comment by gaukas** [comment]
Interesting observation. I think it might worth it if we comment/deprecate on this feature. Apparently we no longer want to remove this exported field since that's already a part of the uTLS API and removing it breaks anyone using an older version and (mistakenly) uses this field in the extension.

**Comment by sleeyax** [comment]
Ah I see. I can create a PR for this small improvement if you like. 

How about adding a deprecation comment  to both `UtlsPreSharedKeyExtension` and `FakePreSharedKeyExtension` structs like this?

```go
type UtlsPreSharedKeyExtension struct {
	// ...

	// Deprecated: Set OmitEmptyPsk in Config instead.
	OmitEmptyPsk bool
}
```

**Comment by gaukas** [comment]
That would be nice! Thanks for doing that.
