### ISSUE TITLE
feat: GREASE ECH Extension

### ISSUE THREAD

**Issue by hax0r31337** [refraction-networking/utls#264]
Chrome browser started shipping with support for Encrypted Client Hello (ECH) recently.   
According to [IETF datatracker](https://datatracker.ietf.org/doc/html/draft-ietf-tls-esni-17#name-grease-ech), it has a feature called GREASE ECH which is enables by default, it also replaced the old Padding extension with a random-generated ECH extension.

**Comment by gaukas** [comment]
Actually this is something we are currently planning to add as a good first step in implementing ECH support for uTLS in terms of parroting.

**Comment by VeNoMouS** [comment]
I've been working on it, its not that easy to implement, learnt quite a bit about it

**Comment by gaukas** [comment]
Sounds good, thanks @VeNoMouS. I am going to push some preliminary progress I have made on this, so possibly we could merge our work.

**Comment by gaukas** [comment]
Merged #266 to add GREASE ECH.
