### ISSUE TITLE
Session tickets from ClientSessionCache are not used

### ISSUE THREAD

**Issue by rod-hynes** [refraction-networking/utls#27]
In testing, it appears that session states/tickets set using `SetSessionCache` are not added to ClientHellos. Individual session states/tickets explicitly set using `SetSessionState` _are_ added to ClientHellos, as long as `SetSessionState` is called before `BuildHandshakeState`.

I suspect the issue with the cache is that `Handshake` calls `BuildHandshakeState` before `clientHandshake` is called here:

https://github.com/refraction-networking/utls/blob/f8425e69f7d4eff4e1988c6c4ca1ca9a6e17a42f/u_conn.go#L182-L189

`clientHandshake` consults the session cache and attempts to use session tickets, but its call to `SetSessionState` comes too late:

https://github.com/refraction-networking/utls/blob/f8425e69f7d4eff4e1988c6c4ca1ca9a6e17a42f/u_conn.go#L312-L334

There's a call to `hello.marshal` after the session cache is checked, but it will just use the previously marshaled value stored in `hello.Raw` set in `MarshalClientHello` which is called by `BuildHandshakeState`:

https://github.com/refraction-networking/utls/blob/f8425e69f7d4eff4e1988c6c4ca1ca9a6e17a42f/u_conn.go#L468

As a result, it appears that TLS session resumption won't work, as session tickets received from servers and stored in the cache will never be sent in ClientHellos?

I didn't try setting a cache directly using `Config.ClientSessionCache`; it appears that would have the same issue?

**Comment by rod-hynes** [comment]
This issue is with TLS 1.2 session tickets. I have not tested TLS 1.3.

Would it be possible to fix by calling `loadSession` in `BuildHandshakeState`? This would preserve the property that the ClientHello is finalized and can be inspected after `BuildHandshakeState` is called.

**Comment by sergeyfrolov** [comment]
> This issue is with TLS 1.2 session tickets. I have not tested TLS 1.3.

Session tickets are obsolete with TLS 1.3, and have been replaced with PSK. I haven't looked deeply into the issue yet, but is it possible that you're trying to add session ticket with TLS 1.3 connection?

**Comment by rod-hynes** [comment]
The case I'm testing is specifically for TLS 1.2 session tickets, so using parrots such as `HelloFirefox_55`.
