### ISSUE TITLE
crypto/ecdh is not in GOROOT (Go 1.18)

### ISSUE THREAD

**Issue by Lynx-1** [refraction-networking/utls#283]
./go/pkg/mod/github.com/refraction-networking/utls@v1.6.1/cfkem.go:25:2: package crypto/ecdh is not in GOROOT (/usr/lib/go-1.18/src/crypto/ecdh)    why?

**Comment by gaukas** [comment]
You need to run at least Go 1.20. That's actually the only reason uTLS is no longer supporting older versions of Go and requiring a minimal version of 1.20 in go.mod.
