### ISSUE TITLE
HTTP2 (akamai) fingerprint always same?

### ISSUE THREAD

**Issue by dr3adx** [refraction-networking/utls#287]
No matter which client hello i use, the http2 / akamai fingerprint is always the same?
How can I change setting such as SETTINGS_HEADER_TABLE_SIZE and all others related to http2 fp? 

Thank you!

**Comment by gaukas** [comment]
In my opinion it might not a part of uTLS. 

I'm not very familiar with HTTP/2, so here's some suggestions that may or may not be helpful:

Determine who sends the related configurations, is it by the TLS client (provisioned by uTLS) during the handshake or by the HTTP roundtripper after TLS handshake is done. 

If the TLS client, you need to determine which extension carries such information and configure the extension. 

If the HTTP roundtripper, please consult the provider of your roundtripper.
