### ISSUE TITLE
How to use proxy

### ISSUE THREAD

**Issue by TroyMicrocode** [refraction-networking/utls#41]
How to use proxy

**Comment by NecronomiconCoding** [comment]
Have you found out how?

**Comment by sergeyfrolov** [comment]
Please consult https://sfrolov.io/blog/2017-08-12-secure-web-proxy-client-en/

**Comment by sergeyfrolov** [comment]
The software in this repository is not a proxy, it is a TLS library.
Instructions on how to use it can be found in README
