### ISSUE TITLE
Using a Proxy to Connect

### ISSUE THREAD

**Issue by NecronomiconCoding** [refraction-networking/utls#42]
Hello, is it possible to connect using HTTP / SOCKS5 Proxy? 
My connection is currently done using default HttpGetConsistentRandomized

**Comment by sergeyfrolov** [comment]
This is a TLS library, it only performs the TLS handshake, and gives you a TLS connection in a form of `net.Conn`, like a standard Golang `net.Dial()` would.
The protocol you speak to your TLS endpoint via that `net.Conn`: HTTP, SOCKS 5, or some other is your choice, but this library has nothing to do with any of those protocols. uTLS only handles TLS
