### ISSUE TITLE
Use Custom TLS Timestamp

### ISSUE THREAD

**Issue by NecronomiconCoding** [refraction-networking/utls#43]
Hi, first off hats off for such an awesome tool! 

Is there any possibility to set a custom Timestamp inside the TLS Handshake instead of the random generated one?

**Comment by sergeyfrolov** [comment]
Are you referring to the timestamp in Client Random?

**Comment by NecronomiconCoding** [comment]
Yes exactly!

**Comment by sergeyfrolov** [comment]
There's no high-level API for this feature (and I don't think any modern tls implementations use it either), but you can generate Client Random yourself and set it.
You can read more about how to do that in README, and in examples/examples.go

**Comment by NecronomiconCoding** [comment]
Yes ive tried that, when settings the random to 0 the it uses the epoch 0 time, that means it uses january 1st 1970. Do you have any idea where its done in any of the libs? I dont mind changing the bytes manually aswell

**Comment by NecronomiconCoding** [comment]
Solved it by replacing the first 4 Bytes with the current time inside MarshalClientHello()

Thanks :)
