### ISSUE TITLE
Use recorded ClientHello messages as templates/fingerprints

### ISSUE THREAD

**Issue by max-b** [refraction-networking/utls#54]
We think it could be useful to generate client hello messages from recorded bytes.

Ideally we would like to contribute this upstream, so I wanted to see if you had any thoughts/concerns/ideas about this approach towards the outset.

We had two ideas about how we might proceed:

### Idea 1
Attempt to create a `ClientHelloSpec` from a `[]byte` slice, something along the lines of: `func FingerPrintClientHello(data []byte) (*ClientHelloSpec, error)`

This seems to mostly require figuring out how to populate the `[]TLSExtension` slice. We could use the `clientHelloMsg.unmarshal` to get information about the Extensions that go's `crypto/tls` library understands/parses, but that leaves us with at least a handful of `[]TLSExtension`s that we'd have to go back through the raw bytes and attempt to re-parse. As we re-parse the hello, we could look specifically for extensions which go doesn't support/parse and then use the `GenericExtension` type to just stuff those bytes into our hello.

It occurs to me that re-parsing likely suffers from 2 problems:
1. I _think_ that our extension could end up out of order from the recorded one?
2. We're basically going to have to move through the whole client hello byte slice anyways in order to parse the generic extensions

At this point it might be worth just writing a parallel `unmarshal` function which does what we need, but I guess I get a little nervy at making a parallel copy of so much core `crypto/tls` code?

### Idea 2
Use the recorded bytes to populate a `clientHelloMsg.raw`, unmarshal those bytes to fill out the rest of the relevant `clientHelloMsg` fields, update `Config` and `UConn` state to reflect any necessary changes, and update the `ClientHello` as appropriate (random, etc). 
In the [Custom Handshake section of the README](https://github.com/refraction-networking/utls#custom-handshake), it says:

> If you need to manually control all the bytes on the wire(certainly not recommended!), you can set UConn.HandshakeStateBuilt = true, and marshal clientHello into UConn.HandshakeState.Hello.raw yourself. In this case you will be responsible for modifying other parts of Config and ClientHelloMsg to reflect your setup and not confuse "crypto/tls", which will be processing response from server.

I'm not actually seeing that field on the `UConn` struct? Additionally, it looks to me that currently `BuildHandshakeState()` and then consequently the `MarshalClientHello()` are called by `Handshake()` and that they will modify raw bytes in any constructed `ClientHelloMsg`

So this approach doesn't seem possible with the current `u_conn.go` behavior and also I worry that it could suffer from some tricky state/config translations.

Thanks so much for your time and patience with this! We'd love to hear what you think about it!

**Comment by sergeyfrolov** [comment]
My intuition is that it should be easy to recreate the function, used by https://tlsfingerprint.io, that hashes ClientHello bytes into a hash ID, e.g. 9c673fd64a32c8dc for Chrome 83 (https://tlsfingerprint.io/id/9c673fd64a32c8dc).  

Then we can create a map of 
9c673fd64a32c8dc -> HelloChrome83 
cab2baf994ded9c9 -> also HelloChrome83
0a4a74aeebd1bb66 -> HelloChrome62
bc4c7e42f4961cd7 -> HelloChrome70
6bfedc5d5c740d58 -> HelloFirefox65

This is similar to your Idea 1, but goes through the numeric ID before being converted an utls.ClientHelloID.
The https://tlsfingerprint.io/ website is not required for this functionality, but it will make management and maintenance of those IDs easier.

**Comment by max-b** [comment]
That sounds like an interesting option. We were actually curious, is the code used by tlsfingerprint.io open source/available somewhere for us to take a look at? I imagine that it must do some intelligent parsing of fields in order to determine which are significant bytes for hashing.

>  The https://tlsfingerprint.io/ website is not required for this functionality, but it will make management and maintenance of those IDs easier.

Agreed, though it seems like it would require additional burdens on the websites/your end? Or do you see an approach that wouldn't involve some additional API changes?

**Comment by sergeyfrolov** [comment]
tlsfingerprint.io code is private for operational reasons, but I am happy to send the parser code to you over e-mail (contact me at sergey.frolov@colorado.edu) or elsewhere. The parser is implemented in Rust, so it would need porting to Golang. It is somewhat intelligent, but not that bad, porting an already existing function sounds to me easier than the alternatives.

Doesn't look like this approach would require any changes to tlsfingerprint.io. It does add an extra function and an extra map to maintain in uTLS, but seems worth it for the more plausible ClientHellos.

**Comment by max-b** [comment]
> tlsfingerprint.io code is private for operational reasons, but I am happy to send the parser code to you over e-mail (contact me at [sergey.frolov@colorado.edu](mailto:sergey.frolov@colorado.edu)) or elsewhere. The parser is implemented in Rust, so it would need porting to Golang. It is somewhat intelligent, but not that bad, porting an already existing function sounds to me easier than the alternatives.

Great - we're familiar enough with Rust over here that I think we should do just fine with that :grin:. I'll send an email shortly - thanks!

> Doesn't look like this approach would require any changes to tlsfingerprint.io. It does add an extra function and an extra map to maintain in uTLS, but seems worth it for the more plausible ClientHellos.

Ah ok yeah I think I understand better what you mean. I'll take a look at the tlsfingerprint.io code - I think that should help make sure I'm on the same page as you.

**Comment by max-b** [comment]
Received your `tls_parser.rs` file - thank you!

I'm still at a bit of a loss for what you'd be interested in pulling into `utls`. It seems as though we'd need to manually maintain a pretty large map of sha hashes->`ClientHelloSpec`s if we did not want to dynamically generate them.

On the other hand, looking at the code you sent over, it seems fairly straightforwards to create something akin to your `ClientHelloFingerprint` struct and then translate that into a `ClientHelloSpec`. I imagine that you are actually doing that somewhere in tlsfingerprint.io when you have the `uTLS generated code` section?

**Comment by sergeyfrolov** [comment]
I don't think this map will be that large or difficult to maintain going forward: whenever I have to add a new fingerprint to uTLS I always have its ID at hand.

That said, solution you propose also should work. I'll share the code for uTLS codegen with you over email
