### ISSUE TITLE
Not actually properly testing omitSNI in u_conn_test

### ISSUE THREAD

**Issue by max-b** [refraction-networking/utls#57]
:facepalm: I feel like an idiot about this one. It looks like I left a hardcoded `false` as the argument here instead of correctly passing through `omitSNI`. I'm honestly a little confused that the compiler allowed it since it's an unused variable.

I'll open a quick PR to fix this. Sorry!!!

https://github.com/refraction-networking/utls/blob/219d12d0a4a1852193b1e0b20e6f4269ec8c5573/u_conn_test.go#L390

**Comment by sergeyfrolov** [comment]
No worries, that happens
