### ISSUE TITLE
tlsfingerprint.io website issues

### ISSUE THREAD

**Issue by tomas324** [refraction-networking/utls#60]
Hi, not sure if this is the right place (apologies if it's not) however https://tlsfingerprint.io/ returns 500 Internal Server Errors on most endpoints and the fingerprinting endpoint https://client.tlsfingerprint.io:8443/ is also down for me.
It was a very useful way to quickly generate a uTLS config, any insight on this would be appreciated.

**Comment by sergeyfrolov** [comment]
It's back up, but something tells me not for long, too much load for our little website

**Comment by 043674543** [comment]
@sergeyfrolov can this be put back online or share the code so people can host on their own servers?
