### ISSUE TITLE
tls: server selected unsupported protocol version 304

### ISSUE THREAD

**Issue by xualen** [refraction-networking/utls#72]
thanks for this library. i use it to connect some website, but response is error( tls: server selected unsupported protocol version 304)
var ja3 = '771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,0-23-65281-10-11-35-16-5-13-18-51-45-43-27-21,29-23-24,0';
var ua = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36';

**Comment by LeBatou** [comment]
I have the same problem and I think that's when the server wants to use TLS_AES_256_GCM_SHA384.
We both have 4866 in our ja3 and when I try to do the request with my phone, the server chose TLS_AES_256_GCM_SHA384

**Comment by qiankunxienb** [comment]
But how to solve this problem?

**Comment by imayberoot** [comment]
@qiankunxienb From my understanding, it's due to there being no HTTP2 support. Other Libraries like MyTLS and Ja3Transport also have this issue. It's something todo with the Ja3 token parsing.
