### ISSUE TITLE
How to Add pre_shared_key  in TLSExtension？

### ISSUE THREAD

**Issue by MYLTLSDDLAM** [refraction-networking/utls#73]
I can't find pre_shared_key in TLSExtension

**Comment by KawaCode** [comment]
Did you find a solution?

**Comment by MYLTLSDDLAM** [comment]
No, but I am trying to write a tls handler by using C#

**Comment by KawaCode** [comment]
Damn it, i am still searching without any success, it seems be really hard to add it. Somewhere in the Codes they have written they will add it once someone asks for it, so i did.

**Comment by MYLTLSDDLAM** [comment]
I tried to send an email to ask writer which write this project in 2020,
but he told me these



There's no need to use fingerprintClientHello, you could use Chrome
fingerprint or randomized one.

What you do need is a some shared secret, that will need to be generated
and shared with the server, such that the server accepts the key and they
client and server can encrypt/decrypt.
Here's an example of this generation for older tls 1.2 session ticket
mechanism, which is very similar to PSK:
https://gist.github.com/oxtoacart/934355309742e80bc624bd21e3858027
Sorry, I never done this for tls 1.3 PSK extension, and don't know the
specifics.

**Comment by MYLTLSDDLAM** [comment]
It was in 2021,not 2020, sorry about that

**Comment by yuzd** [comment]
Does somebody find a solution?
