### ISSUE TITLE
tlsfingerprint.io backend returns incorrect stats

### ISSUE THREAD

**Issue by Warren772** [refraction-networking/utls#83]
from my testing on multiple devices, [https://client.tlsfingerprint.io:8443/](https://client.tlsfingerprint.io:8443/) no longer returns the correct stats. from what i see, `cluster , cluster_seen, seen, seen_total, frac_seen, rank, custer_fps & clusterfrac` are all returning erroneous values, i cannot assess the validity of the other values returned.

**Comment by leiless** [comment]
I can confirm this.

**Comment by Warren772** [comment]
Endpoint correctly working, closing issue!
