### ISSUE TITLE
tlsfingerprint.io status

### ISSUE THREAD

**Issue by VeNoMouS** [refraction-networking/utls#99]
Hi,

Does anyone have any idea of the status of tlsfingerprint.io? it seems the cluster / database is dead... there are no id's on the site... client.tlsfingerprint.io does not work...

if this site is now dead, will it be made open source? it was a really great tool to use... and if it is indeed dead, it a very sad day for the security community

**Comment by 043674543** [comment]
happy to host if you require

**Comment by GunGunGun** [comment]
Alternative is Wireshark, but I would like to see this website again. Do you know any local server alternative that list all cipher+extension like tlsfingerprint.io ?

**Comment by wwhtrbbtt** [comment]
https://tls.peet.ws/api/all is a decent alternative :)

**Comment by gaukas** [comment]
Since we now have a repository ([refraction-networking/tls-fingerprint](https://github.com/refraction-networking/tls-fingerprint)) for the site now, we could close it for now. And hopefully the site downtime could be further reduced with optimized software and structure.
